version: '3'
services:
  node-app:
    env_file:
    - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: movie_review_db
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: movie_review_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db_data: